## Import Numpy module
We generally use **np** alias for numpy module.

In [0]:
import numpy as np

## Create 1-Dimensional array (Vector)
We can use a python list as an input to create a 1-D array.

In [2]:
l = [1, 2, 3]
l

[1, 2, 3]

In [3]:
a = np.array(l)
a

array([1, 2, 3])

## Shape of 1-D array

In [4]:
a.shape

(3,)

## Creating 2-Dimensional Array (Matrix)
We can use a list of lists i.e. nested lists to create a 2-D array. This can also be called a matrix.    
We have to remember however that the size of each nested list should be same.

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
a2 = np.array(my_mat)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Shape of 2-D Array

In [9]:
a2.shape

(3, 3)

## Numpy function to create serial numbers
Create a list of serial number with specified interval, the default being 1. The last number in the parameter is **not included** in the produced list.  
*Do mind the spelling!*

In [10]:
np.arange(0, 10)  # A list from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)  # A list from 0 to 8 with 2 interval

array([0, 2, 4, 6, 8])

## Random number generation
Generate a random floating point number i.e. a number with a "." in it. The number lies within 0 and 1.  
It takes as input the dimension of the array required.

*The numbers are generated from the standard normal distribution but it's okay if you do not know what that is. You can read more about it [here](http://www.oswego.edu/~srp/stats/z.htm).*

1-D array with length 4

In [0]:
np.random.randn(4)

array([ 0.77059006,  0.60377975, -1.03161901, -0.94801423])

2-D array with 5 rows, 4 columns

In [0]:
np.random.rand(5, 4)

array([[0.68235154, 0.91480001, 0.58051852, 0.43167709],
       [0.72881904, 0.32313912, 0.41414342, 0.37387187],
       [0.26667587, 0.15197729, 0.42568444, 0.52214776],
       [0.87857887, 0.11546472, 0.47237783, 0.66167113],
       [0.9621082 , 0.89368289, 0.77127208, 0.11226247]])

## Random Integer generation
Generate a random integer array of specified dimension. We also need to specify the range from which the number is generated.  
By default only 1 number will be generated. *To specify a dimension of 2 or more, you need and extra pair of small brackets.*

Random number from 1 to 10

In [0]:
np.random.randint(1, 10)

6

1-D Array with 5 random elements between 1 to 10

In [0]:
np.random.randint(1, 10, 5)

array([5, 7, 3, 3, 2])

2-D Array with 2 rows and 3 columns with random number between 1 to 10

In [0]:
np.random.randint(1, 10, (2, 3))

array([[5, 5, 6],
       [6, 8, 2]])

## Seed (Consistent randomness)
We might need to reproduce results in AI while still requiring random numbers. For such cases, we use numpy seed.  
The sequence of numbers generated after using seed will always follow the same but pseudo-random pattern.

In [0]:
np.random.seed(10)
np.random.randint(1, 10, 7)

array([5, 1, 2, 1, 2, 9, 1])

## Reshape
An array can be reshaped to any other dimensions given that the total number of elements remain the same.  
For example, a 1-D array with 12 elements can be converted to shapes: (2, 6), (3, 4), (4, 3), (12, 1), (2, 2, 3) and so on, because the total number of elements remain the same in all of these cases.

In [0]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

A 1-D array with 12 elements

In [0]:
arr.shape  

(12,)

A 2-D array with a total of 3 x 4 = 12 elements

In [0]:
arr.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Indexing
Indexing can be done using just the numeral position of the required element inside the square box.  
*Remember that the index starts from **0** and not 1.*

In [0]:
s = np.arange(0, 10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
s[1]

1

We can also index from the end by using the minus **-** sign. If we want the last element we can use *-1*, if we want the second last element we can use *-2* and so on.

In [0]:
s[-3]

7

## Slicing
Slicing can be done using the colon **:** operator. The last index however, is not included in the output.  
*Again, remember that index starts from 0.*

In [0]:
s[1:5]

array([1, 2, 3, 4])

There is an easier method for slicing if the slicing takes place from the beginning or from any intermediate element up to the last element.  
Also, similar to before, if the index is placed afer the **:**, it is not included in the output.

From beginning up to the index 4 (*5th element)*.

In [0]:
s[:5]

array([0, 1, 2, 3, 4])

From index 3 *(4th element)* up to the last element.

In [0]:
s[3:]

array([3, 4, 5, 6, 7, 8, 9])

We can also use the negative indexing in slicing. Also, similar to before, if the index is placed afer the **:**, it is not included in the out

In [0]:
s[-2:]

array([8, 9])

In [0]:
s[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Assignment
We can use the indexing and slicing method to change their value. All the elements which are output by the left side of the operator are changed to the value on the right.

In [0]:
j = np.arange(10, 20)
j

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [0]:
j[0:5] = 100
j

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19])

In [0]:
h = j[:7]
h

array([100, 100, 100, 100, 100,  15,  16])

To change all the values, use can just use the **:** operator without any index.

In [0]:
h[:] = 5
h

array([5, 5, 5, 5, 5, 5, 5])

## Copying
We should remember that by default the address of the variable is copied such i.e. numpy arrays are *mutable*.

In [0]:
j

array([ 5,  5,  5,  5,  5,  5,  5, 17, 18, 19])

If we want to copy just the values without changing the original variable, use *copy* function.

In [0]:
jc = np.copy(j)
jc

array([ 5,  5,  5,  5,  5,  5,  5, 17, 18, 19])

In [0]:
jc[6:] = 100
jc

array([  5,   5,   5,   5,   5,   5, 100, 100, 100, 100])

The original variable will not change like before

In [0]:
j

array([ 5,  5,  5,  5,  5,  5,  5, 17, 18, 19])

## Indexing  in multi-dimensional array
Similar to 1-D array, there is index/slicing for each dimension.  
The index/slicing can either be separated by a comma **,** or can be specified in different square boxes altogether.  
*Index starts from 0.*

In case of 2-D array, the first index/slice is for the row and the second index/slice is for the column of the selected rows.

In [0]:
np.random.seed(1)
abc = np.random.randint(1, 10, (3, 6))
abc

array([[6, 9, 6, 1, 1, 2],
       [8, 7, 3, 5, 6, 3],
       [5, 3, 5, 8, 8, 2]])

In [0]:
abc[0, 0]

6

In [0]:
abc[0][0]

6

In [0]:
abc[0]

array([6, 9, 6, 1, 1, 2])

In [0]:
abc

array([[6, 9, 6, 1, 1, 2],
       [8, 7, 3, 5, 6, 3],
       [5, 3, 5, 8, 8, 2]])

In [0]:
abc[2, 2]

5

In [0]:
abc[:2, 1:]

array([[9, 6, 1, 1, 2],
       [7, 3, 5, 6, 3]])

In [0]:
abc[2:, 2:]

array([[5, 8, 8, 2]])

# Vectors operations

## Dot Product

In [0]:
v1 = np.array([3, 4])
v2 = np.array([5, 12])

Magnitude

In [0]:
v1_mag = np.linalg.norm(v1)
v1_mag

5.0

In [0]:
v2_mag = np.linalg.norm(v2)
v2_mag

13.0

Dot product

In [0]:
np.dot(v1, v2)

63

Cos angle

In [0]:
cos = np.dot(v1, v2) / ( v1_mag * v2_mag)
cos

0.9692307692307692

Angle in radian

In [0]:
angle_r = np.arccos(cos)

Angle in degrees

In [0]:
angle_d = (180 * angle_r) / np.pi
angle_d

14.250032697803595

## Cross product

In [0]:
vc = np.cross(v1, v2)
vc

array(16)

In [0]:
vc_mag = np.linalg.norm(vc)
vc_mag

16.0

In [0]:
v1_mag = np.linalg.norm(v1)
v2_mag = np.linalg.norm(v2)

In [0]:
sin = vc_mag / ( v1_mag * v2_mag)
sin

0.24615384615384617

In [0]:
theta_r = np.arcsin(sin)
theta_r

0.24870998909352288

In [0]:
theta_d = (180 * theta_r) / np.pi
theta_d

14.250032697803595

## Matrix Inverse

In [0]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [0]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Matrix Determinant

In [0]:
A_det = np.linalg.det(A)
A_det

-2.0000000000000004

## Diagonal Elements

In [0]:
A

array([[1, 2],
       [3, 4]])

In [0]:
np.diag(A)

array([1, 4])

## Creating Diagonal Matrix

In [0]:
np.diag([1, 2])

array([[1, 0],
       [0, 2]])